### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by lzap** [theforeman/ruby-newt#2]
There are two memory leaks at the moment.

First, form and grid objects have destroy/free functions which are currently not called. Make sure GC collections will not error out.

Second, some memory is allocated with `ALLOCA_N` but never returned (multiple places)

**Comment by rtgill82** [comment]
I believe I have nearly complete test coverage and valgrind logs seem to show that no memory leaks originate in the `ruby-newt` module, but only in the interpreter internals. I'm assuming this is just lazy de-allocation by the interpreter and it's just allowing the OS to clean up after it exits.

[valgrind.log](https://github.com/theforeman/ruby-newt/files/7742062/valgrind.log)

**Comment by rtgill82** [comment]
Was performing some more memory testing. Callbacks seem to fail when the garbage collector is run manually.

**Comment by rtgill82** [comment]
valgrind still claims the leaks are in the interpreter itself, but I managed to fix the issue with the callbacks.

**Comment by lzap** [comment]
Let's close this one then, looks better now for sure.
