### ISSUE TITLE
Gem should include examples (or documentation)

### ISSUE THREAD

**Issue by fwolfst** [theforeman/ruby-newt#4]
Hi guys
and thanks for taking over the gem!

More often than I'd wish I cannot access the internet and am super-happy in those cases if the gems I installed came with some sort of documentation or examples.

Thus, I opt to take in the `examples` folder into the gem. I believe I'd manage to create a PR if you'd wish.

Thanks,
Felix

**Comment by lzap** [comment]
Sure, please go ahead and make the required change. Also, we need a lot more tests if you are interested. The code still contains some leaks which we need to take care of!
